// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_bsvarSIGNs_H_GEN_
#define RCPP_bsvarSIGNs_H_GEN_

#include "bsvarSIGNs_RcppExports.h"

#endif // RCPP_bsvarSIGNs_H_GEN_
