# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

niw_cpp <- function(A, SIGMA, Y, X, S, prior_A, prior_V, prior_S, prior_nu) {
    invisible(.Call(`_bsvarSIGNs_niw_cpp`, A, SIGMA, Y, X, S, prior_A, prior_V, prior_S, prior_nu))
}

matnrnd_cpp <- function(M, U, V) {
    .Call(`_bsvarSIGNs_matnrnd_cpp`, M, U, V)
}

qr_sign_cpp <- function(A) {
    .Call(`_bsvarSIGNs_qr_sign_cpp`, A)
}

rortho_cpp <- function(N) {
    .Call(`_bsvarSIGNs_rortho_cpp`, N)
}

irf_cpp <- function(posterior_B, posterior_A, horizon, p) {
    .Call(`_bsvarSIGNs_irf_cpp`, posterior_B, posterior_A, horizon, p)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bsvarSIGNs_RcppExport_registerCCallable`)
})
