# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmatnorm_cpp <- function(M, U, V) {
    .Call(`_bsvarSIGNs_rmatnorm_cpp`, M, U, V)
}

riwish_cpp <- function(S, nu) {
    .Call(`_bsvarSIGNs_riwish_cpp`, S, nu)
}

niw_cpp <- function(Y, X, prior) {
    .Call(`_bsvarSIGNs_niw_cpp`, Y, X, prior)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_bsvarSIGNs_RcppExport_registerCCallable`)
})
